---
- hosts: all
  tasks:
  - name: Upgrade all packages (yum)
    yum: name=* state=latest
    when: ansible_os_family == "RedHat"
  - name: remote /usr/share/java directory for all cluster nodes
    file:
      path: /usr/share/java
      state: directory
  - name: install the latest version of httpd
    yum:
      name: httpd
      state: latest
  - name: Stop service httpd, if started
    service:
      name: httpd
      state: started
      enabled: yes
  - name: stop  service firewalld ,disable when os reboot
    service:
      name: firewalld
      state: stopped
      enabled: no
  - name: install the latest version of wget package
    yum:
      name: wget
      state: latest
  - name: Installing Ntp packages
    yum:
      name: ntp
      state: latest
    yum:
      name: libtirpc-devel
      state: present
  - name: selinux disabling
    selinux:
      state: disabled
  - name: Disable THP support scripts added to rc.local
    lineinfile:
      path: /etc/rc.local
      line: |
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
        echo never > /sys/kernel/mm/transparent_hugepage/defrag
  - name: Change permissions of /etc/rc.local to make it run on boot
    shell: chmod +x /etc/rc.d/rc.local
  - name: Set swappiness to 1
    sysctl: name=vm.swappiness value=1 state=present ignoreerrors=yes
  - name: Disable the tuned Service
    action: shell systemctl start tuned
    action: shell tuned-adm off
    action: shell systemctl stop tuned
    action: shell systemctl disable tuned
  - name: Download mysql-java.jar
    get_url:
      url: https://downloads.mysql.com/archives/get/file/mysql-connector-java-6.0.6.tar.gz
      dest: /usr/share/java/
  - name: Extract mysql-connector-java-6.0.6.tar.gz into /usr/share/java/
    unarchive:
      src: /usr/share/java/mysql-connector-java-6.0.6.tar.gz
      dest: /usr/share/java
  - name: Rename the mysql-connector-java-6.0.6-bin.jar into mysql-connector-java.jar
    command: mv /usr/share/java/mysql-connector-java-6.0.6/mysql-connector-java-6.0.6-bin.jar /usr/share/java/mysql-connector-java.jar
  - name: copy hosts entry file my remote cluster nodes
    copy:
      src: /etc/hosts
      dest: /etc/
- hosts: all
  tasks:
  - name: adding ambari.repo file in yum.repos.d location
    get_url:
      url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.3.0/ambari.repo
      dest: /etc/yum.repos.d/
  - name: updating yum repolist
    shell: sh /root/ambari.sh
- hosts: master
  tasks:
  - name: Ambari-server installing on master node AND MYSQL INSTALLATION
    yum: 
      name: ambari-server
      state: latest
  - name: Ambari-agent installing on master node
    yum:
      name: ambari-agent
      state: latest
  - name: mysql-connector setup to ambari-server
    command: ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar
  - name: installing the Mysql-server using shell script
    command: sh /root/mysql.sh
- hosts: all
  tasks:
  - name: On Client nodes installing ambari-agent
    yum:
      name: ambari-agent
      state: latest
...
