---
- hosts: master
  tasks:
    - name: adding ambari.repo file in yum.repos.d location
      get_url:
        url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.3.0/ambari.repo
        dest: /etc/yum.repos.d/
...
